# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introduction to Sensors and Data
author: Ryan C. Cooper, Martin Huber, Shubhangi Bansude
logo: sensors_logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
parse:
    myst_extended_syntax: true


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex


launch_buttons:
  notebook_interface        : "classic"  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
#  jupyterhub_url            : https://compmech.uconn.edu  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "" # The URL of Google Colab (https://colab.research.google.com)

# Information about where the book exists on the web
repository:
  url: https://github.com/cooperrc/sensors_and_data # Online location of your book
  #path_to_book:   # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
